[package]
name = "mif"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
dotenvy = "0.15.7"
serenity = { version = "0.12.0", features = ["client", "gateway", "rustls_backend", "model"] }
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio-native-tls"]}
poise = "0.6.1"
time = { version = "0.3.36", features = ["parsing", "local-offset"]}
tokio = { version = "1.26.0", features = ["full", "rt-multi-thread"]}
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
lru = "0.12.4"
